// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgcmgyobgotbxautlfhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnY21neW9iZ290YnhhdXRsZmhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1Njc2NjIsImV4cCI6MjA1NDE0MzY2Mn0.9pBaUVhlt7AWhYZKbOshM6tjLOvQQaeg6rAvzMSB020";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);